"""Add state column to Scheme

Revision ID: 12e6a2fbb545
Revises: f42c95667564
Create Date: 2025-11-25 13:43:07.396976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e6a2fbb545'
down_revision: Union[str, Sequence[str], None] = 'f42c95667564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemes', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'state')
    # ### end Alembic commands ###
